os: linux
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "Qt/5.6.2"
    - CONAN_USERNAME: "bilke"
    - CONAN_CHANNEL: "testing"
    - CONAN_TOTAL_PAGES: 2
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS: 4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 5.3 CONAN_USE_DOCKER=1

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode8
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode7.1
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode6.2
      language: generic
      env: CONAN_CURRENT_PAGE=1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

before_script:
  - chmod +x .travis/before_script.sh
  - ./.travis/before_script.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
